version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hoverplay-demo.rule=Host(`demo.hoverplay.net`)"
      - "traefik.http.routers.hoverplay-demo.entrypoints=websecure"
      - "traefik.http.routers.hoverplay-demo.tls=true"
      - "traefik.http.services.hoverplay-demo.loadbalancer.server.port=5000"
    networks:
      - webproxy

networks:
  webproxy:
    external: true
